# CONFIGURACIONES
apiVersion: v1
kind: Secret
metadata:
  name: database
stringData:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: keycloak
  POSTGRES_DB: database
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_PASSWORD: "password"
  PGADMIN_OIDC_CLIENT_SECRET: "keycloak"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: admin@domain.com
  PGADMIN_LISTEN_ADDRESS : "0.0.0.0"
  PGADMIN_LISTEN_PORT: "8080"
  PGADMIN_CONFIG_SERVER_MODE: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "True"
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2', 'internal']"
  PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: "True"
  PGADMIN_OIDC_CLIENT_ID: pgadmin
---  
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_PASSWORD: password
  TEST_USER: test #user_key
  TEST_PASSWORD: prueba
  GF_ADMIN_USERNAME: grafana
  GF_ADMIN_PASSWORD: grafana
  PGADMIN_CLIENT_SECRET: super-secret
---  
# realms a importar
# realms a importar
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
data:
  KC_REALM_NAME: "dev"
  realm.json: >
    {
    "id": "dev",
    "realm": "dev",
    "sslRequired": "none",
    "enabled": true,
    "eventsEnabled": true,
    "eventsExpiration": 900,
    "adminEventsEnabled": true,
    "adminEventsDetailsEnabled": true,
    "attributes": {
      "adminEventsExpiration": "900"
    },
    "roles": {
      "realm": [],
      "client": {
        "desa-cli": [],
        "grafana": [
          {
            "id": "ff2a9eab-8e39-4660-b6d8-40b09269bffc",
            "name": "editor",
            "description": "Grafana editor",
            "composite": false,
            "clientRole": true,
            "attributes": {}
          },
          {
            "id": "ff2a9eab-8e39-4660-b6d8-40b09269bffb",
            "name": "admin",
            "description": "Grafana admin",
            "composite": false,
            "clientRole": true,
            "attributes": {}
          },
          {
            "id": "ff2a9eab-8e39-4660-b6d8-40b09269bffa",
            "name": "viewer",
            "description": "Grafana viewer",
            "composite": false,
            "clientRole": true,
            "attributes": {}
          },
          {
            "id": "ff2a9eab-8e39-4660-b6d8-40b09269bfff",
            "name": "grafanaadmin",
            "description": "Grafana Super User",
            "composite": false,
            "clientRole": true,
            "attributes": {}
          }
        ]
      }
    }, 
    "groups": [],
    "users": [
      {
        "id": "dev-test-user",
        "username": "${TEST_USER}",
        "enabled": true,
        "emailVerified": true,
        "firstName": "${TEST_USER}",
        "lastName": "USER",
        "email": "${TEST_USER}@mail.localdev.me",
        "credentials": [
          {
            "temporary": false,
            "type": "password",
            "value": "${TEST_PASSWORD}"
          }
        ],
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "realmRoles": [],
        "notBefore": 0,
        "groups": [],
        "clientRoles": {
          "grafana": [
            "grafanaadmin"
          ]
        }
      },
      {
        "id": "grafana-admin",
        "email": "${GF_ADMIN_USERNAME}@admin",
        "username": "${GF_ADMIN_USERNAME}",
        "enabled": true,
        "emailVerified": true,
        "credentials": [
          {
            "temporary": false,
            "type": "password",
            "value": "${GF_ADMIN_PASSWORD}"
          }
        ],
        "clientRoles": {
          "grafana": [
            "grafanaadmin"
          ]
        }
      }
    ],
    "clients": [
      {
        "id": "desa-cli",
        "clientId": "desa-cli",
        "name": "Desa Client",
        "description": "",
        "rootUrl": "http://localhost:3178",
        "adminUrl": "http://localhost:3178",
        "baseUrl": "",
        "enabled": true,
        "publicClient": true,
        "redirectUris": [
          "*"
        ],
        "webOrigins": [
          "*"
        ]
      },
      {
        "id": "grafana",
        "clientId": "grafana",
        "name": "grafana",
        "enabled": true,
        "publicClient": true,
        "redirectUris": [
          "*"
        ],
        "webOrigins": [
          "*"
        ],"protocolMappers" : [ {
          "id": "fb2a9eab-8eaa-4660-b6d8-40b09269b122",
          "name" : "client roles",
          "protocol" : "openid-connect",
          "protocolMapper" : "oidc-usermodel-client-role-mapper",
          "consentRequired" : false,
          "config" : {
            "multivalued" : "true",
            "userinfo.token.claim" : "true",
            "id.token.claim" : "true",
            "access.token.claim" : "true",
            "claim.name" : "roles",
            "jsonType.label" : "String",
            "usermodel.clientRoleMapping.clientId" : "grafana"
          }
        } ]

      },
      {
        "clientId": "pgadmin",
        "surrogateAuthRequired": false,
        "enabled": true,
        "alwaysDisplayInConsole": false,
        "clientAuthenticatorType": "client-secret",
        "secret": "${PGADMIN_OIDC_CLIENT_SECRET}",
        "redirectUris": [
          "*"
        ],
        "webOrigins": [
          "*"
        ],
        "bearerOnly": false,
        "consentRequired": false,
        "standardFlowEnabled": true,
        "implicitFlowEnabled": false,
        "directAccessGrantsEnabled": false,
        "serviceAccountsEnabled": true,
        "publicClient": false,
        "frontchannelLogout": false,
        "protocol": "openid-connect",
        "defaultClientScopes": ["openid","roles","profile","email"],
        "optionalClientScopes": ["address","offline_access"],
        "name" : "pgAdmin Client"
      }
    ],
    "smtpServer": {}
    }
